language: python

python: 2.7

env:
  - TOXENV=py27-django19
  - TOXENV=py27-django_trunk
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django_trunk
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django_trunk

install:
  - pip install --upgrade pip setuptools tox virtualenv coveralls

script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=py27-django_trunk
    - env: TOXENV=py34-django_trunk
    - env: TOXENV=py35-django_trunk

after_success: coveralls
